version: "3.8"
services:
 backend:
  container_name: laravel
  build:
   context: ./backend
   dockerfile: Dockerfile
  restart: always
  volumes:
   - ./backend:/var/www/html/backend
   - enlive-vendor:/var/www/html/backend/vendor
  depends_on:
   - db
  networks:
   - app


 frontend:
  container_name: next_app
  build:
   context: ./frontend
   dockerfile: Dockerfile
  restart: unless-stopped
  volumes:
   - ./frontend:/var/www/html/frontend
  depends_on:
   - backend
  networks:
   - app

 db:
  container_name: db
  image: postgres:latest
  restart: unless-stopped
  ports:
   - "5432:5432"
  volumes:
   - db:/var/lib/postgresql/data
  environment:
   - POSTGRES_DB=testxdebug
   - POSTGRES_USER=root
   - POSTGRES_PASSWORD=root
  networks:
   - app

 phppgadmin:
  container_name: phppgadmin
  image: dpage/pgadmin4:latest
  restart: always
  ports:
   - "5050:80"
  environment:
   # - POSTGRES_HOST=postgres
   - PGADMIN_DEFAULT_EMAIL=admin@admin.com
   - PGADMIN_DEFAULT_PASSWORD=root
   # - PGADMIN_LISTEN_ADDRESS=0.0.0.0
   # - PGADMIN_LISTEN_PORT=5050
   - POSTGRES_PORT=5432
   - POSTGRES_USER=testxdebuguser
   - POSTGRES_PASSWORD=secret
  depends_on:
   - db
  networks:
   - app
  tty: true


 nginx:
  container_name: nginx
  image: nginx:latest
  restart: unless-stopped
  ports:
   - "8080:80"
  volumes:
   - ./backend:/var/www/html/backend
   - enlive-vendor:/var/www/html/backend/vendor
   - ./frontend:/var/www/html/frontend
   - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  depends_on:
   - frontend
  networks:
   - app

networks:
 app:
  driver: bridge

volumes:
 db:
  driver: local
 enlive-vendor:
